### ISSUE TITLE
Set up AutoMerge on the BioJuliaRegistry

### ISSUE THREAD

**Issue by DilumAluthge** [BioJulia/BioJuliaRegistry#29]
Since you already have your own BioJulia installation of Registrator.jl, you might find it helpful to set up AutoMerge on the BioJuliaRegistry.

cc: @BenJWard

**Comment by TransGirlCodes** [comment]
@DilumAluthge I've set it up on this registry using a similar config to General, but with BioJuliaBot as the PR author instead of JuliaRegistrator, and I've added General as a dependency. From the actions logs I can see it considers PR 22, and decides to not auto-merge it, but it does not post on PR 22 listing the things that need to be fixed like you see in General PRs. Is that just because this PR predates setting up AutoMerge or is there something cricial I've missed?

**Comment by DilumAluthge** [comment]
@BenJWard Can you make a new registration? I’ll take a look.

**Comment by DilumAluthge** [comment]
> Is that just because this PR predates setting up AutoMerge

If the PR was made before you set up AutoMerge, simply close and reopen the PR. This will trigger AutoMerge on the PR.

**Comment by TransGirlCodes** [comment]
Awesome it appeared on #22, thanks @DilumAluthge, I'll close this now.
